### PR TITLE
allowing for auto generation of sites attributes

### LINKED ISSUE #136: optional sites options, like in phpstack
Certain virtualhost fields (e.g., ServerAlias) need to be configured as an optional field (i.e., does not have to be defined at all).

https://github.com/rackspace-cookbooks/phpstack/pull/286

### PR DESCRIPTION
**Pull request by prometheanfire**
fixes #136

Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by prometheanfire** [comment]
test this please

**Comment by jujugrrr** [comment]
Please see my comment on https://github.com/rackspace-cookbooks/phpstack/pull/286

**Comment by prometheanfire** [comment]
test this please

**Comment by prometheanfire** [comment]
test this please

**Comment by prometheanfire** [comment]
test this please

**Comment by prometheanfire** [comment]
test this please

**Comment by jujugrrr** [comment]
@cybermerc Could we wait for the comment to be answered next time before to merge?

Thank you

**Pull request merged**
